version: '3'
services:
  web:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - db
      - redis
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - '5432:5432' # Adicione esta linha para permitir acesso externo ao PostgreSQL
    networks:
      - mynetwork
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379' # Adicione esta linha para permitir acesso externo ao Redis
    networks:
      - mynetwork

networks:
  mynetwork:
